//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTLNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class RideStop
    {
        public int RideStop_Id { get; set; }
        public int Ride_Id { get; set; }
        public int RouteStop_Id { get; set; }
        public Nullable<System.DateTime> DateTime_Departure { get; set; }
        public Nullable<System.DateTime> DateTime_Arrival { get; set; }
    
        public virtual Ride Ride { get; set; }
        public virtual RouteStop RouteStop { get; set; }
    }
}
