//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTLNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteStop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RouteStop()
        {
            this.RideStop = new HashSet<RideStop>();
        }
    
        public int RouteStop_Id { get; set; }
        public int Route_Id { get; set; }
        public int Stop_Id { get; set; }
        public int Position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RideStop> RideStop { get; set; }
        public virtual Route Route { get; set; }
        public virtual Stop Stop { get; set; }
    }
}
